### ISSUE TITLE
MGLIdeographicFontFamilyName should accept font display or PostScript name

### ISSUE THREAD

**Issue by chloekraw** [mapbox/mapbox-gl-native-ios#105]
Developers who use `localIdeographFontFamily` and specify a `text-font` with "Bold" in the name on some layers are expecting the text of those layers to show up as bolded on iOS, just like they do on Web and Android.

It looks like we did add a `CoreText`-based `LocalGlyphRasterizer` implementation on darwin in https://github.com/mapbox/mapbox-gl-native/pull/10572, but for some reason, passing in different font weight values doesn't actually change the font weight: https://github.com/mapbox/mapbox-gl-native/pull/10572#issuecomment-347995568. So, this ticket tracks debugging this issue further.

---

Note that the existing implementations are slightly different due to limitations on each platform:

To achieve this effect on Android, we use the platform API `android.graphics.Typeface` in `LocalGlyphRasterizer` to draw the glyphs locally. `Typeface` only supports a limited number of formatting options (bold, bold italic, italic, normal) in API 14 (our minimum deployment target) and does not support the specification of a numeric weight value until API 28. 

On GL-JS, we [check](https://github.com/mapbox/mapbox-gl-js/blob/master/src/render/glyph_manager.js#L145) the name of the font on each layer and change the `fontWeight` if the font's name contains the word "Bold", "Medium", or "Light":

```
 if (!tinySDF) {
            let fontWeight = '400';
            if (/bold/i.test(stack)) {
                fontWeight = '900';
            } else if (/medium/i.test(stack)) {
                fontWeight = '500';
            } else if (/light/i.test(stack)) {
                fontWeight = '200';
            }
            tinySDF = entry.tinySDF = new GlyphManager.TinySDF(24, 3, 8, .25, family, fontWeight);
        }
```

**Comment by chloekraw** [comment]
@mapbox/maps-ios there's a request to reach GL JS parity (see OP) with our implementation of font-weight in LocalGlyphRasterizer: https://github.com/mapbox/mapbox-gl-native-ios/blob/master/platform/darwin/src/local_glyph_rasterizer.mm#L29

Apparently Android APIs may prevent us from supporting `Medium` and potentially other weights, and I'm thinking we should reach parity with Android over JS. Any concerns about the possibility of implementing this?

cc @mapbox/maps-android

**Comment by chloekraw** [comment]
I poked around the git commit history and it looks like we did add a `CoreText`-based `LocalGlyphRasterizer` implementation on iOS in https://github.com/mapbox/mapbox-gl-native/pull/10572, but for some reason, passing in different font weight values doesn't actually change the font weight: https://github.com/mapbox/mapbox-gl-native/pull/10572#issuecomment-347995568 

I'm updating the OP of this ticket to match the actual work that would need to happen.

cc @kkaefer

**Comment by 1ec5** [comment]
> Developers who use `localIdeographFontFamily` and specify a `text-font` with "Bold" in the name on some layers are expecting the text of those layers to show up as bolded on iOS, just like they do on Web and Android.

As stated in [this documentation](https://docs.mapbox.com/ios/api/maps/5.7.0/infoplist-keys.html#mglideographicfontfamilyname), `MGLIdeographicFontFamilyName` expects a font family name. (By comparison, GL JS relies on the [`font-family`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family) CSS property, which despite its name can be set to an individual font’s display name or PostScript name in most browsers.)

If you instead specify a display name or PostScript name, the SDK won’t send any font family name to mbgl due to this validation step in `-[MGLRendererConfiguration _localFontFamilyNameWithPropertyDictionary:]`:

https://github.com/mapbox/mapbox-gl-native-ios/blob/87fac0bb3447872bb142c57b4d12b4b7cb9b31f7/platform/darwin/src/MGLRendererConfiguration.mm#L110

It would be possible to check against `NSFontManager.availableFonts` in addition to `availableFontFamilies` to accept PostScript names. (On iOS, we’d need to call `+[UIFont fontNamesForFamilyName:]` for each of the family names returned by `UIFont.familyNames`.)

There isn’t a performant way to obtain the display names of every installed font on the system, but a common approach to accepting display names or PostScript names is to create an `NSFontDescriptor`/`UIFontDescriptor`, then attempt to create a font using `+[NSFont fontWithDescriptor:size:]`/`+[UIFont fontWithDescriptor:size:]`. As it happens, this is exactly what `mbgl::LocalGlyphRasterizer::Impl::getFont()` does:

https://github.com/mapbox/mapbox-gl-native/blob/6bed2079e3097336547ac01dda3768caadf0c441/platform/darwin/src/local_glyph_rasterizer.mm#L72-L78

`kCTFontFamilyNameAttribute` is set to a name that doesn’t match any installed font _families_. So `CTFontCreateWithFontDescriptor()` will return the default font, Helvetica, and `mbgl::LocalGlyphRasterizer::Impl::drawGlyphBitmap()` will use the system’s font cascade list.

I don’t think `-[MGLRendererConfiguration _localFontFamilyNameWithPropertyDictionary:]` should validate `MGLIdeographicFontFamilyName` values, since `mbgl::LocalGlyphRasterizer::Impl::getFont()` is going to do so anyways, just using Core Text instead of AppKit/UIKit. The only reason it seems to do so is that we added support for a cascading list after the fact, so mbgl only stores a single font family name.

A better solution would be to pass all the names into mbgl verbatim. Then, mbgl would create a font descriptor for each name interpreted as a font family name, font display name, and font PostScript name, in that order. Each of these font descriptors would go into a `kCTFontCascadeListAttribute`, which we’d set instead of or in addition to `kCTFontAttributeName`.

/ref https://github.com/mapbox/mapbox-gl-native/pull/14862#issuecomment-500994073

**Comment by 1ec5** [comment]
> On GL-JS, we [check](https://github.com/mapbox/mapbox-gl-js/blob/master/src/render/glyph_manager.js#L145) the name of the font on each layer and change the `fontWeight` if the font's name contains the word "Bold", "Medium", or "Light":

I’m not sure why this is necessary, because the JavaScript implementation of TinySDF relies on the [`font-family`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family) CSS property, which despite its name can be set to an individual font’s display name or PostScript name in most browsers.

**Comment by 1ec5** [comment]
> Do we need to support only 'Bold' style or other font styles as well?

This is quite feasible as long as we rely on the system to match each `MGLIdeographicFontFamilyName` to the available fonts, rather than sniffing the weight out of the display name. For example, here’s Noto Sans CJK JP Black, using the cascade list approach outlined in https://github.com/mapbox/mapbox-gl-native-ios/issues/105#issuecomment-592991225:

<img width="869" alt="black" src="https://user-images.githubusercontent.com/1231218/75621935-9b0bb080-5b4f-11ea-84df-9774869f2744.png">

The Hiragino font families have numeric weights, not keywords, in the display names. Here’s Hiragino Sans W9:

<img width="869" alt="w9" src="https://user-images.githubusercontent.com/1231218/75621976-0a81a000-5b50-11ea-9fba-40a445416334.png">

Note that few CJK fonts come with an explicit “italic” style font. Instead, it’s common for a specific, cursive-like style to be distributed as the normal font in a separate font family.

**Comment by 1ec5** [comment]
> I poked around the git commit history and it looks like we did add a `CoreText`-based `LocalGlyphRasterizer` implementation on iOS in https://github.com/mapbox/mapbox-gl-native/pull/10572, but for some reason, passing in different font weight values doesn't actually change the font weight: https://github.com/mapbox/mapbox-gl-native/pull/10572#issuecomment-347995568

The assumption during that PR’s development was that there would be an installed font family named “PingFang” that includes a font face with the style “Bold”. In fact, Apple systems come with a font family named “PingFang HK”, “PingFang SC”, or “PingFang TC”, with the styles “Thin”, “Light”, “Ultralight”, “Regular”, “Medium”, and “Semibold”. Nothing seemed to happen, because Core Text couldn’t find a font face matching either criteria. Instead, it fell back to the first CJK font in the cascade list, which happened to be PingFang TC Regular: https://github.com/mapbox/mapbox-gl-native/pull/16253#issuecomment-593133491.

It is possible to create a font based on a font family name and a font weight, as the commented-out, since-removed `getFontWeight()` method in mapbox/mapbox-gl-native#10572 attempted to do. However, we need to create the font descriptor using the `kCTFontTraitsAttribute` and `kCTFontWeightTrait` keys rather than the `kCTFontStyleNameAttribute` key. `kCTFontStyleNameAttribute` performs an exact match on the font faces’ declared styles without any interpolation.

It’s also possible to create a font based on a font family name and font style name. As it happens, we can count on a JSON symbol layer’s `text-font` layout property to generally contain font display names, since Studio normalizes the values to display names. So this would be the most robust cascade list (in order):

1. Each of the `text-font` values verbatim as font display names or PostScript names, except for Arial Unicode MS
1. Each of the `MGLIdeographicFontFamilyName` values:
   1. as a font display name or font PostScript name
   1. as a font family name with a font style name parsed from `text-font`

The idea is that, if the developer has uploaded a custom font to Studio, they would prefer the SDK to use an identically named font that they’ve bundled with the application or that is already installed on the system. `MGLIdeographicFontFamilyName` should be thought of as a stylistic fallback, not an override, even though it does override the mechanism for obtaining the font.

I think these heuristics would be more intuitive and better respect Studio’s role in the design process, but we’d need to make sure it doesn’t represent a backwards-incompatible change and doesn’t put developers in a catch-22 if they also want the same style JSON to render using the same fonts on other platforms.

**Comment by 1ec5** [comment]
It’s also possible to create a font based on a font family name and font style name. As it happens, we can count on a JSON symbol layer’s `text-font` layout property to generally contain font display names, since Studio normalizes the values to display names. So this would be the most robust cascade list (in order):

1. Each of the `text-font` values verbatim as font display names or PostScript names, except for Arial Unicode MS
1. Each of the `MGLIdeographicFontFamilyName` values:
   1. as a font display name or font PostScript name
   1. as a font family name with a font style name parsed from `text-font`

The idea is that, if the developer has uploaded a custom font to Studio, they would prefer the SDK to use an identically named font that they’ve bundled with the application or that is already installed on the system. `MGLIdeographicFontFamilyName` should be thought of as a stylistic fallback, not an override, even though it does override the mechanism for obtaining the font.

I think these heuristics would be more intuitive and better respect Studio’s role in the design process, but we’d need to make sure it doesn’t represent a backwards-incompatible change and doesn’t put developers in a catch-22 if they also want the same style JSON to render using the same fonts on other platforms.

**Comment by 1ec5** [comment]
I still think sniffing traits out of (freeform) font display names is an error-prone approach that will come back to haunt us when we expand local font rendering to scripts beyond CJK – in which case “Italic”, “Condensed”, “Mono”, etc. all become common enough that we’d have to detect these keywords too.

As a first step, I’m going to add font stack awareness to mapbox/mapbox-gl-native#16253 but leave out the sniffing bit:

1. Each of the values in the font stack verbatim as a font display name or PostScript name or font family name, except for Arial Unicode MS
1. Each of the `MGLIdeographicFontFamilyName` values as a font display name or font PostScript name or font family name
