### ISSUE TITLE
It is invalid to switch traditional languages

### ISSUE THREAD

**Issue by CorkiiOS** [mapbox/mapbox-gl-native-ios#169]
- (void)mapView:(MGLMapView *)mapView didFinishLoadingStyle:(MGLStyle *)style {
    [style localizeLabelsIntoLocale:nil];
}

I find that other languages can be switched, so why can't traditional languages be switched.

**Comment by 1ec5** [comment]
Hi @CorkiiOS, thanks for reporting this issue. A few questions to help us understand what you’re experiencing:

* What version of the map SDK are you using?
* What is the preferred language in Settings?
* What language is your application running in? (This may differ from the preferred language, based on the localizations your application provides.)
* What happens when you call [`-localizeLabelsIntoLocale:`](https://docs.mapbox.com/ios/api/maps/5.7.0/Classes/MGLStyle.html#/c:objc%28cs%29MGLStyle%28im%29localizeLabelsIntoLocale:) this way? Does your application crash, or do the labels remain in the wrong language?

Note that a locale of `nil` should cause the map’s labels to appear in the user’s preferred language in Settings. A locale of `[NSLocale localeWithIdentifier:@"mul"]` would cause each label to appear in the locally appropriate language (for example, French labels in France but German labels in Germany). Is this not what you’re seeing?

**Comment by CorkiiOS** [comment]
version 5.5.0
The preferred language is traditional Chinese
The application runtime language is traditional

My steps：
1.Switch to English
2.Switch to traditional Chinese
Then the map shows English

My code:
(void)mapView:(MGLMapView *)mapView didFinishLoadingStyle:(MGLStyle *)style {
[style localizeLabelsIntoLocale:nil];
}
