### ISSUE TITLE
Display labels only in a given area on the map

### ISSUE THREAD

**Issue by jeudesprits** [mapbox/mapbox-gl-native-ios#290]
I would like to hide all labels that go beyond the status bar. Now, labels are displayed directly under the status bar, which sometimes greatly interferes:

![image](https://user-images.githubusercontent.com/36597778/80700436-2de8ad00-8af7-11ea-9edf-bf7bc161b489.jpeg)

**Comment by 1ec5** [comment]
This is a very interesting and reasonable idea. The default visual effect of a UIVisualEffectView, UIVibrancyEffect, is designed to magnify drastic changes in color, which is no problem for most text labels but can be problematic for shields, as you’ve discovered. MapKit apparently does exclude shields from the status bar area, probably by rendering them into a different CALayer.

<img src="https://user-images.githubusercontent.com/1231218/80742348-1649fe00-8ad0-11ea-973b-66b3ba26fe05.jpg" width="300" alt="mapkit">

Unfortunately, I’m not sure how we’d go about implementing a mask for just the status bar area, because shields in Mapbox GL are really part of the same base map rendered by OpenGL, not something we can separate into its own CALayer. mapbox/mapbox-gl-js#6267 proposes adding something to the style specification to invert a fill layer. Mapbox GL doesn’t currently support any compositing effects, so we’re limited to approaches that operate on entire features, not individual symbols like shields.

Just brainstorming some workarounds in order of ickiness:

* Consider switching that UIVisualEffectView’s effect to UIBlurEffect, which makes the shields more discernible but perhaps not as eye-catching.
* Change the color of these shields or hide them at zoom levels where you think the user might notice them under the status bar.
* If you don’t expect much interaction, you could try to stick an MGLMapSnapshot underneath the status bar that uses a similar style with no shields. But this approach would perform poorly if the map will be panned and zoomed frequently.

**Comment by jeudesprits** [comment]
> Mapbox GL doesn’t currently support any compositing effects, so we’re limited to approaches that operate on entire features, not individual symbols like shields.

But what if we remove absolutely all labels? Not just shields. 
Is it possible? Because the problem is not only in shields, but also in rather bold inscriptions.

**Comment by 1ec5** [comment]
You can hide or remove anything from the style, all the way down to a blank style, by editing the style JSON (such as in Mapbox Studio), calling `-[MGLStyle removeLayer:]`, or setting `MGLStyleLayer.visible`. Can you hide or remove whole layers (e.g., every feature road label) or only features within that layer (e.g., individual highway shields) that match a certain condition. The problem is that the condition can’t be based on whether the feature happens to be at the top of the screen.
