### ISSUE TITLE
Need to Replace UIWebView with WKWebView

### ISSUE THREAD

**Issue by akshaySwarajya** [mapbox/mapbox-gl-native-ios#300]
As per Apple guideline, from 30th April, 2020 every app must replace UIWebView with WKWebView.

Mapbox-iOS-SDK  contains UIWebView. Thats why Apple Review team not accepting new apps.

**Comment by 1ec5** [comment]
[The SDK does not make use of UIWebView](https://github.com/mapbox/mapbox-gl-native-ios/search?q=UIWebView&unscoped_q=UIWebView). If your App Store submission is getting rejected, can you double-check your other dependencies for UIWebView usage?

**Comment by akshaySwarajya** [comment]
I tried 

> grep -r "UIWebView" . 

command in project directory and found one match..

> Binary file ./Pods/Mapbox-iOS-SDK/dynamic/Mapbox.framework.dSYM/Contents/Resources/DWARF/Mapbox matches

**Comment by 1ec5** [comment]
Thank you for the additional detail. Are you getting a rejection from the App Store or TestFlight due to this dSYM?

The only two places where the SDK comes close to using WebKit are:

* [Converting HTML to an NSAttributedString](https://github.com/mapbox/mapbox-gl-native-ios/blob/a13921663715be33907a9c1bdb8e220a43e03a83/platform/darwin/src/MGLAttributionInfo.mm#L68-L87) as part of converting attribution in TileJSON to a structured format. Under the hood, this conversion process does use WebKit but not UIWebView.
* [This errant import statement](https://github.com/mapbox/mapbox-events-ios/blob/5c955a030d0dad8b55c89a33d8502c49f001f72f/MapboxMobileEvents/MMEEventLogger.m#L6) of WebKit’s umbrella header in MapboxMobileEvents, which is statically linked into the SDK. The include is unused and would not affect the built binary. (Incidentally, the import statement was removed in mapbox/mapbox-events-ios#197 for a forthcoming version of that library).

https://github.com/mapbox/ios-sdk-examples/issues/373#issuecomment-551918113 and https://github.com/mapbox/mapbox-gl-native/issues/15559#issuecomment-528128516 go into more detail about why UIWebView appears in the dSYM. But I don’t see anything when running `nm Pods/Mapbox-iOS-SDK/dynamic/Mapbox.framework/Mapbox | grep -i UIWebView`, which is what the App Store checks are supposed to be looking at. Do you get any results for that?

If the only results you’re getting are in Mapbox.framework.dSYM and Apple is rejecting your submission because of that file, make sure your project is including that file correctly. CocoaPods normally does not add the .dSYM file to your project as a file reference, but it is an input file and output file to the “[CP] Embed Pod Frameworks” build phase, which copies the .dSYM to `${DWARF_DSYM_FOLDER_PATH}/Mapbox.framework.dSYM`.

**Comment by akshaySwarajya** [comment]
Apple review team rejected app from App Store.

**Comment by akshaySwarajya** [comment]
Apple approved app.

**Comment by OldestDriver** [comment]
> Apple approved app.

Hello, I also encountered this problem, how do you solve it?

**Comment by GIovaB6** [comment]
> our project as a file reference,

me too
