### ISSUE TITLE
Compass progressively increases in size

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native-ios#53]
When `Bold Text` is enabled in `Settings -> Display & Brightness`, the compass view will progressively increase in size when the following code is repeatedly called:

```
mapView.compassViewMargins = margins
mapView.layoutSubviews()
```

**Comment by m-stephen** [comment]
It seems that system will resize view's bounds when app set 'Bold Text'. Once the superview is calling `layoutSubviews`, the subview's bounds will progressively increase by this call stack:
```
    frame #0: 0x000000010291b330 Mapbox`::-[MGLCompassButton setBounds:](self=0x000000010e442420, _cmd="setBounds:", bounds=(origin = (x = 0, y = 0), size = (width = 41, height = 41))) at MGLCompassButton.mm:38:5
    frame #1: 0x00000001a6831098 UIKitCore`-[UIView(Geometry) _applyISEngineLayoutValuesToBoundsOnly:] + 532
    frame #2: 0x00000001a6831468 UIKitCore`-[UIView(Geometry) _resizeWithOldSuperviewSize:] + 140
    frame #3: 0x00000001a22857b0 CoreFoundation`__NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ + 24
    frame #4: 0x00000001a2183460 CoreFoundation`-[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 432
    frame #5: 0x00000001a6830568 UIKitCore`-[UIView(Geometry) resizeSubviewsWithOldSize:] + 172
    frame #6: 0x00000001a6774364 UIKitCore`-[UIView(AdditionalLayoutSupport) _is_layout] + 152
    frame #7: 0x00000001a6838374 UIKitCore`-[UIView(Hierarchy) _updateConstraintsAsNecessaryAndApplyLayoutFromEngine] + 1048
    frame #8: 0x000000010292a6c4 Mapbox`::-[MGLMapView layoutSubviews](self=0x000000010f003000, _cmd="layoutSubviews") at MGLMapView.mm:970:5
    frame #9: 0x000000010244071c MapExperience`-[ViewController viewWillAppear:](self=0x000000010e424860, _cmd="viewWillAppear:", animated=YES) at ViewController.m:129:5
    frame #10: 0x00000001a5d5bf48 UIKitCore`-[UIViewController _setViewAppearState:isAnimating:] + 652
    frame #11: 0x00000001a5d5c5fc UIKitCore`-[UIViewController __viewWillAppear:] + 128
```

So after testing, this problem is not only occurred on compass view, but also logo view & attribution Button:

![image](https://user-images.githubusercontent.com/2045318/68456869-e6652080-0239-11ea-8d3b-cefbbf0dd57f.png)


Since we update the width/height constraints by the view's bounds when it is setting margins, the width/height constraints will progressively increase. I'll change the update constraints logic to fix this issue temporarily and still need to observe this change bounds behavior. I'm not sure it is an Apple's bug or not. 

Feel free for any suggestions. @fabian-guerra @julianrex
